"""
ARBITER Claims Intelligence Report Generator
"""

import io
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import base64

DARK = colors.HexColor("#0d1117")
AMBER = colors.HexColor("#f59e0b")
RED = colors.HexColor("#ef4444")
GREEN = colors.HexColor("#10b981")
BLUE = colors.HexColor("#3b82f6")
GRAY = colors.HexColor("#6b7280")
LIGHT_GRAY = colors.HexColor("#f3f4f6")
WHITE = colors.white
BORDER = colors.HexColor("#e5e7eb")


def generate_report(claim_id: str, result: dict, image_b64: str = None) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=20*mm, leftMargin=20*mm,
        topMargin=25*mm, bottomMargin=25*mm,
    )
    styles = _build_styles()
    story = []

    story.extend(_build_header(claim_id, result, styles))
    story.append(Spacer(1, 8*mm))
    story.extend(_build_verdict_banner(result, styles))
    story.append(Spacer(1, 6*mm))

    verdict = result.get("verdict", {})
    ruling = verdict.get("ruling", "")
    if ruling:
        story.append(Paragraph(f'<i>"{ruling}"</i>', styles["ruling"]))
        story.append(Spacer(1, 6*mm))

    story.append(Paragraph("Forensic Signal Analysis", styles["section_title"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 3*mm))
    story.extend(_build_score_table(result, styles))
    story.append(Spacer(1, 6*mm))

    story.append(Paragraph("AI Forensic Debate", styles["section_title"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 3*mm))
    story.extend(_build_debate_section(result, styles))
    story.append(Spacer(1, 6*mm))

    story.append(Paragraph("Detailed Technical Findings", styles["section_title"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 3*mm))
    story.extend(_build_findings(result, styles))

    story.append(Spacer(1, 8*mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Spacer(1, 3*mm))
    disclaimer = ("This report was generated by ARBITER AI Forensic Intelligence System. "
                  "Results represent probabilistic assessments and should be reviewed by a qualified claims adjuster. "
                  "ARBITER does not make final legal determinations.")
    story.append(Paragraph(disclaimer, styles["disclaimer"]))

    doc.build(story, onFirstPage=_page_template, onLaterPages=_page_template)
    buffer.seek(0)
    return buffer.read()


def _build_styles():
    return {
        "title": ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=20, textColor=DARK, spaceAfter=2),
        "subtitle": ParagraphStyle("subtitle", fontName="Helvetica", fontSize=10, textColor=GRAY, spaceAfter=4),
        "section_title": ParagraphStyle("section_title", fontName="Helvetica-Bold", fontSize=12, textColor=DARK, spaceBefore=4, spaceAfter=4),
        "body": ParagraphStyle("body", fontName="Helvetica", fontSize=9, textColor=DARK, leading=14),
        "mono": ParagraphStyle("mono", fontName="Courier", fontSize=8, textColor=DARK, leading=12),
        "ruling": ParagraphStyle("ruling", fontName="Helvetica-Oblique", fontSize=10, textColor=GRAY, leading=14, leftIndent=10, rightIndent=10),
        "disclaimer": ParagraphStyle("disclaimer", fontName="Helvetica", fontSize=7, textColor=GRAY, leading=10),
        "verdict_label": ParagraphStyle("verdict_label", fontName="Helvetica-Bold", fontSize=11, textColor=WHITE, alignment=TA_CENTER),
        "risk_score": ParagraphStyle("risk_score", fontName="Helvetica-Bold", fontSize=28, textColor=WHITE, alignment=TA_CENTER),
        "flag_text": ParagraphStyle("flag_text", fontName="Helvetica", fontSize=8, textColor=colors.HexColor("#92400e"), leading=12),
    }


def _build_header(claim_id: str, result: dict, styles: dict) -> list:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    fraud_type = result.get("verdict", {}).get("fraud_type", "UNKNOWN")
    header_data = [[
        Paragraph("ARBITER", styles["title"]),
        Paragraph(f"Claim ID: <b>{claim_id}</b><br/>Generated: {now}", styles["subtitle"])
    ]]
    t = Table(header_data, colWidths=["60%", "40%"])
    t.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE"), ("ALIGN", (1, 0), (1, 0), "RIGHT")]))
    return [t,
            Paragraph("AI Forensic Claims Intelligence Report", styles["subtitle"]),
            Paragraph(f"Fraud Typology Assessment: <b>{fraud_type}</b>", styles["subtitle"])]


def _build_verdict_banner(result: dict, styles: dict) -> list:
    verdict = result.get("verdict", {})
    action = verdict.get("action", "FLAG")
    risk_score = verdict.get("risk_score_percent", 0)
    risk_level = verdict.get("risk_level", "MEDIUM")
    color_map = {"REJECT": RED, "FLAG": AMBER, "AUTO_APPROVE": GREEN}
    bg_color = color_map.get(action, GRAY)
    banner_data = [[
        Paragraph("RECOMMENDED ACTION", styles["verdict_label"]),
        Paragraph(f"{action}", ParagraphStyle("action", fontName="Helvetica-Bold", fontSize=18, textColor=WHITE, alignment=TA_CENTER)),
        Paragraph("RISK SCORE", styles["verdict_label"]),
        Paragraph(f"{risk_score}/100", styles["risk_score"]),
        Paragraph("RISK LEVEL", styles["verdict_label"]),
        Paragraph(f"{risk_level}", ParagraphStyle("level", fontName="Helvetica-Bold", fontSize=14, textColor=WHITE, alignment=TA_CENTER)),
    ]]
    t = Table(banner_data, colWidths=["17%", "17%", "17%", "17%", "16%", "16%"])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg_color),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    return [t]


def _build_score_table(result: dict, styles: dict) -> list:
    scores = result.get("layer_scores", {})
    verdict = result.get("verdict", {})
    breakdown = verdict.get("breakdown", {})
    header = [Paragraph("<b>Signal</b>", styles["body"]), Paragraph("<b>Method</b>", styles["body"]),
              Paragraph("<b>Score</b>", styles["body"]), Paragraph("<b>Weight</b>", styles["body"]),
              Paragraph("<b>Assessment</b>", styles["body"])]
    rows = [header]
    signal_methods = {
        "ela": "JPEG Error Level Analysis",
        "fft": "FFT Frequency Energy Ratio",
        "phash": "Perceptual Hash Deduplication",
        "clip": "CLIP Text-Image Cosine Similarity",
        "mahalanobis": "DINOv2 Mahalanobis Distance",
        "temporal": "EXIF / GPS Metadata Audit",
    }
    for sig, method in signal_methods.items():
        if sig in scores:
            sc = scores[sig]
            bd = breakdown.get(sig, {})
            score_val = sc.get("fraud_score", 0)
            label = sc.get("label", "")
            rows.append([
                Paragraph(sig.upper(), styles["mono"]),
                Paragraph(method, styles["body"]),
                Paragraph(f"{score_val:.3f}", styles["body"]),
                Paragraph(f"{bd.get('weight', 0)*100:.0f}%", styles["body"]),
                Paragraph(label, styles["body"]),
            ])
    if "sam" in scores:
        sam = scores["sam"]
        rows.append([
            Paragraph("SAM", styles["mono"]),
            Paragraph("Damage Severity Segmentation", styles["body"]),
            Paragraph(f"{sam.get('severity_percent', 0):.1f}%", styles["body"]),
            Paragraph("INFO", styles["body"]),
            Paragraph(sam.get("severity_class", ""), styles["body"]),
        ])
    t = Table(rows, colWidths=["15%", "35%", "12%", "12%", "26%"])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), LIGHT_GRAY),
        ("GRID", (0, 0), (-1, -1), 0.25, BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return [t]


def _build_debate_section(result: dict, styles: dict) -> list:
    debate = result.get("debate", {})
    prosecutor = debate.get("prosecutor", {}).get("arguments", "N/A")
    defender = debate.get("defender", {}).get("arguments", "N/A")
    debate_data = [
        [Paragraph("PROSECUTION", ParagraphStyle("p", fontName="Helvetica-Bold", fontSize=9, textColor=RED, alignment=TA_CENTER)),
         Paragraph("DEFENSE", ParagraphStyle("d", fontName="Helvetica-Bold", fontSize=9, textColor=GREEN, alignment=TA_CENTER))],
        [Paragraph(prosecutor, styles["body"]), Paragraph(defender, styles["body"])],
    ]
    t = Table(debate_data, colWidths=["50%", "50%"])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#fef2f2")),
        ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#f0fdf4")),
        ("GRID", (0, 0), (-1, -1), 0.25, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return [t]


def _build_findings(result: dict, styles: dict) -> list:
    items = []
    scores = result.get("layer_scores", {})
    temporal = scores.get("temporal", {})
    for flag in (temporal.get("flags") or []):
        items.append(Paragraph(f"⚠ {flag}", styles["flag_text"]))
    fft = scores.get("fft", {})
    if fft.get("generator_type") and fft.get("generator_type") != "NATURAL_CAMERA":
        items.append(Paragraph(f"⚠ Generator fingerprint: {fft['generator_type']} — R_HF={fft.get('r_hf', 'N/A')}", styles["flag_text"]))
    phash = scores.get("phash", {})
    if phash.get("matched_claim"):
        items.append(Paragraph(f"⚠ Image matches claim {phash['matched_claim']} — hash distance: {phash.get('hash_distance', 'N/A')}", styles["flag_text"]))
    if not items:
        items.append(Paragraph("No critical flags detected.", styles["body"]))
    return items


def _page_template(canvas_obj, doc):
    canvas_obj.saveState()
    page_num = canvas_obj.getPageNumber()
    canvas_obj.setFont("Helvetica", 8)
    canvas_obj.setFillColor(GRAY)
    canvas_obj.drawRightString(doc.pagesize[0] - 20*mm, 15*mm, f"ARBITER Forensic Report — Page {page_num} — CONFIDENTIAL")
    canvas_obj.restoreState()
